version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: allrev_postgres
    environment:
      POSTGRES_DB: allrev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespass
    ports:
      - '5432:5432'
    volumes:
      - pgdata_allrev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: allrev_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # Porta padr√£o do NestJS
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgrespass
      DB_NAME: allrev
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata_allrev:
